const mongoose = require("mongoose");

const userOrderSchema = new mongoose.Schema(
  {
    order_id: String,
    // product_id: String,
    // product_image: String,
    event_date: String,
    booking_from: String,
    event_start_date: String,
    event_end_date: String,
    event_name: String,
    number_of_days: Number,
    // event_address: String,
    google_maplink: String,
    upload_invitation: String,
    upload_gatepass: String,
    receiver_name: String,
    receiver_mobilenumber: String,
    // product_price: Number,
    // applied_quantity: Number,
    // totalPrice: Number,
    product_data: Array,
    service_data: Array,
    tech_data: Array,
    // product_mrp: Number,
    // product_name: String,
    user_id: String,
    user_name: String,
    user_mailid: String,
    user_mobile_number: String,
    venue_name: String,
    venue_open_time: String,
    location_lat: {
      type: mongoose.Types.Decimal128,
      default: null,
      // required: true,
    },
    location_long: {
      type: mongoose.Types.Decimal128,
      default: null,
      // required: true,
    },
    event_location: String,
    event_start_time: String,
    event_end_time: String,
    // cart_value: Number,
    cart_total: Number,
    base_amount: Number,
    gst_applied_value: Number,
    tds_deduction: Number,
    amount_after_deduction: Number,
    paid_amount: Number,
    payment_method: String,
    order_status: String,
    payment_status: String,
    cancel_reason: String,
    return_reason: String,
    reason_command: String,
    returned_date: String,
    cancelled_date: String,
    stock_in_hand: Number,
    vendors_message: String,
    event_setup: [
      {
        vendor_id: String,
        vendor_name: String,
        image_type: String,
        image_url: String,
        createdDate: String,
      },
    ],
    ordered_date: { type: Date },
    returned_date: { type: Date },
    delivered_date: { type: Date },
    rescheduled_date: { type: Date },
    reschedule_remark: String,
  },
  {
    timestamps: true,
  }
);

const UserOrder = mongoose.model("UserOrder", userOrderSchema);

module.exports = UserOrder;
